apiVersion: secrets.hashicorp.com/v1beta1
kind: HCPVaultSecretsApp
metadata:
  name: cloudflared-hcpvaultsecretsapp
  labels:
      {{- include "hcp-secret-operator.labels" . | nindent 4}}
spec:
  appName: cloudflared
  destination:
    create: true
    name: cloudflared-secret
  hcpAuthRef: hcpauth
  refreshAfter: 1h