apiVersion: secrets.hashicorp.com/v1beta1
kind: HCPVaultSecretsApp
metadata:
  name: product-svc-hcpvaultsecretsapp
  labels:
      {{- include "hcp-secret-operator.labels" . | nindent 4}}
spec:
  appName: product-svc
  destination:
    create: true
    name: product-svc-secret
  hcpAuthRef: hcpauth
  refreshAfter: 1h