apiVersion: secrets.hashicorp.com/v1beta1
kind: HCPVaultSecretsApp
metadata:
  name: redis-hcpvaultsecretsapp
  labels:
      {{- include "hcp-secret-operator.labels" . | nindent 4}}
spec:
  appName: redis
  destination:
    create: true
    name: redis-secret
  hcpAuthRef: hcpauth
  refreshAfter: 1h