FROM maven:3.9.8-eclipse-temurin-17 AS app-builder
ARG SERVICE_NAME
ENV JAR_PATH=/build/target/${SERVICE_NAME}-0.0.1-SNAPSHOT.jar
WORKDIR build
COPY . .
RUN mvn clean package -q -DskipTests && \
    java -Djarmode=tools -jar $JAR_PATH extract --layers --launcher --destination layers

FROM eclipse-temurin:17-jdk-alpine AS jre-builder
RUN  jlink --verbose --add-modules ALL-MODULE-PATH --strip-debug --no-man-pages --no-header-files --compress=2 --output /jre

FROM alpine:3.20.3@sha256:beefdbd8a1da6d2915566fde36db9db0b524eb737fc57cd1367effd16dc0d06d
ENV JAVA_HOME=/jre
ENV PATH="$JAVA_HOME/bin:$PATH"
COPY --from=jre-builder /jre $JAVA_HOME
ARG SERVICE_PORT
WORKDIR /opt/app
RUN adduser -D -s /bin/bash app
COPY --from=app-builder --chown=app:app --chmod=500 /build/layers/dependencies/ ./
COPY --from=app-builder --chown=app:app --chmod=500 /build/layers/spring-boot-loader/ /build/layers/snapshot-dependencies /build/layers/application ./
EXPOSE ${SERVICE_PORT}
LABEL org.opencontainers.image.source=https://github.com/ngodat0103/yamp
LABEL  org.opencontainers.image.description="YAMP - Yet Another Microservice Project"
LABEL  org.opencontainers.image.source=https://github.com/ngodat0103/yamp
LABEL  org.opencontainers.image.title=YAMP
LABEL  org.opencontainers.image.url=https://github.com/ngodat0103/yamp
ENTRYPOINT ["java", "org.springframework.boot.loader.launch.JarLauncher"]