FROM maven:3.9.8-eclipse-temurin-17 AS builder
ARG SERVICE_NAME
ENV JAR_PATH=/build/target/${SERVICE_NAME}-0.0.1-SNAPSHOT.jar
WORKDIR build
COPY . .
RUN mvn  clean package -q -DskipTests
RUN jar -xf $JAR_PATH
RUN jdeps --ignore-missing-deps --print-module-deps --multi-release 17 --recursive --class-path 'BOOT-INF/lib/*' $JAR_PATH >modules.txt
RUN jlink --verbose --add-modules $(cat modules.txt) --output /jre --compress 2 --no-header-files
FROM eclipse-temurin:17-jre AS layers
ARG SERVICE_NAME
ENV JAR_PATH=/build/target/${SERVICE_NAME}-0.0.1-SNAPSHOT.jar
WORKDIR /
COPY --from=builder $JAR_PATH app.jar
RUN java -Djarmode=tools -jar app.jar extract --layers --launcher --destination layers

FROM debian:12.7-slim@sha256:a629e796d77a7b2ff82186ed15d01a493801c020eed5ce6adaa2704356f15a1c
ENV JAVA_HOME=/jre
ENV PATH="$JAVA_HOME/bin:$PATH"
COPY --from=builder /jre $JAVA_HOME
ARG SERVICE_PORT
WORKDIR /opt/app
COPY --from=layers /layers/dependencies/ ./
COPY --from=layers /layers/spring-boot-loader/ ./
COPY --from=layers /layers/snapshot-dependencies/ ./
COPY --from=layers /layers/application/ ./
#RUN useradd -r -s /usr/sbin/nologin -d /opt/app app && \ # this command increase the image size by 129.84MB, I don't know why
#    chown -R app:app /opt/app
USER app
EXPOSE ${SERVICE_PORT}
LABEL org.opencontainers.image.source=https://github.com/ngodat0103/yamp
LABEL  org.opencontainers.image.description="YAMP - Yet Another Microservice Project"
LABEL  org.opencontainers.image.source=https://github.com/ngodat0103/yamp
LABEL  org.opencontainers.image.title=YAMP
LABEL  org.opencontainers.image.url=https://github.com/ngodat0103/yamp
ENTRYPOINT ["java", "org.springframework.boot.loader.launch.JarLauncher"]