apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      imagePullSecrets:
        - name: registry-secret
      containers:
        - name: auth-container
          image: registry-harbor.ngodat0103.me/kltn/auth-service:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 8001