apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql-staging-infra-yamp-application
  namespace: argocd
spec:
  project: default
  source:
    helm:
      parameters:
        - name: global.postgresql.auth.existingSecret
          value: share-db-secret
        - name: global.postgresql.auth.secretKeys.adminPasswordKey
          value: adminPasswordKey
    chart: postgresql
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 15.5.29
  destination:
    server: https://kubernetes.default.svc
    namespace: staging-infra-yamp
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-staging-infra-yamp-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: kafka
    targetRevision: 30.0.5
    helm:
      values: |
        fullnameOverride: kafka-svc
        listeners:
          client:
            protocol: PLAINTEXT # I'm new to this, so I set it to PLAINTEXT, in the future, I will change it to SASL_SSL. Currently, I focus how to make it work.
  destination:
    server: https://kubernetes.default.svc
    namespace: staging-infra-yamp
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true

