apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-staging-infra-yamp-application
  namespace: argocd
spec:
  project: default
  source:
    chart: vault-secrets-operator
    repoURL: https://helm.releases.hashicorp.com/
    targetRevision: 0.8.1
  destination:
    server: https://kubernetes.default.svc
    namespace: prod-infra-yamp
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: HCPAuth
metadata:
  name: hcpauth
  namespace: prod-infra-yamp
spec:
  organizationID: cbe1cf74-4825-4a1b-8c63-c685c98f813c
  projectID: d0064e9e-e611-4d22-8151-d54a515c513d
  servicePrincipal:
    secretRef: hcp-k8s-operator-principal-secret
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: HCPVaultSecretsApp
metadata:
  name: postgres-hcpvaultsecretsapp
  namespace: prod-infra-yamp
spec:
  appName: share-db
  destination:
    create: true
    name: share-db-secret
  hcpAuthRef: hcpauth
  refreshAfter: 1h