spring:
  config:
    activate:
      on-profile: demo
  cloud:
    gateway:
      httpclient:
        connect-timeout: 1000
        response-timeout: 5s
  data:
    redis:
      url: redis://redis-svc:6379
      client-type: lettuce
      database: 1
      client-name: gateway-service
  security:
    oauth2:
      client:
        provider:
#          auth-service-internal:
#            authorization-uri: http://auth-svc:8001/api/v1/auth/oauth2/authorize
#            token-uri: http://auth-svc:8001/api/v1/auth/oauth2/token
#            jwk-set-uri: http://auth-svc:8001/api/v1/auth/oauth2/jwks
          auth-service-external:
            authorization-uri: http://localhost:8000/api/v1/auth/oauth2/authorize
            token-uri: http://localhost:8000/api/v1/auth/oauth2/token
            jwk-set-uri: http://localhost:8000/api/v1/auth/oauth2/jwks

        registration:
          gateway-service:
            redirect-uri: "http://localhost:8000/login/oauth2/code/gateway-service"
            provider: auth-service-external
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_basic
            client-id: gateway-service
            client-secret: "gateway-service-secret"
            scope: user.read,openid,profile,message.read,message.write
      resourceserver:
        jwt:
          authorities-claim-name: "roles"
          authority-prefix: "ROLE_"
          jwk-set-uri: http://auth-svc:8001/api/v1/auth/oauth2/jwks


logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"
  level:
    com.github.ngodat0103.yamp.gateway: DEBUG
    org.springframework.security: DEBUG
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /ui-docs
    enabled: true
    oauth:
      client-id: swagger-client
      client-secret: "swagger-client-secret"
      use-basic-authentication-with-access-code-grant: true
    oauth2-redirect-url: http://localhost:8000/webjars/swagger-ui/oauth2-redirect.html
    urls:
      - name: "auth-service"
        url: "http://localhost:8000/api/v1/auth/api-docs"
      - name: "user-service"
        url: "http://localhost:8000/api/v1/user/api-docs"
    use-root-path: true
