spring:
  data:
    redis:
      url: redis://redis-svc:6379
      client-type: lettuce
      database: 1
      client-name: gateway-service
  config:
    activate:
      on-profile: integration-test
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true