spring:
  sleuth:
    sampler:
      probability: 1.0
  config:
    activate:
      on-profile: local-dev
  cloud:
    inetutils:
      default-hostname: "yamp-backend.local"
    gateway:
      routes:
        - id: user-svc
          uri: http://user-svc:8002
          predicates:
            - Path=/api/v1/users/**,/api/v1/address/**,/api/v1/user-address/**,/api/v1/countries/**
#        - id: product-svc
#          uri: http://localhost:8003
#          predicates:
#            - Path=/api/v1/product/**
  #          filters:
  #            - name: RequestRateLimiter
  #              args:
  #                redis-rate-limiter.replenishRate: 1
  #                redis-rate-limiter.burstCapacity: 1
  #                redis-rate-limiter.requestedTokens: 1
  #            - name: Retry
  #              args:
  #                method: GET
  #                backoff:
  #                  firstBackoff: 100ms
  #                  maxBackoff: 1000ms
  #                  factor: 2
  #            - name: CircuitBreaker
  #              args:
  #                name: user-service-breaker
  #                fallbackUri: forward:/fallback
  data:
    redis:
      url: redis://redis-svc:6379
      client-type: lettuce
      database: 1
      client-name: gateway-svc
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /ui-docs
    enabled: true
    oauth:
      use-basic-authentication-with-access-code-grant: true
      client-id: ${CLIENT_ID}
      client-secret: ${CLIENT_SECRET}

    oauth2-redirect-url: http://${spring.cloud.inetutils.default-hostname}:${server.port}/webjars/swagger-ui/oauth2-redirect.html
    urls:
      - name: "auth-svc"
        url: "http://${spring.cloud.inetutils.default-hostname}:${server.port}/api/v1/auth/api-docs"
      - name: "user-svc"
        url: "http://${spring.cloud.inetutils.default-hostname}:${server.port}/api/v1/users/api-docs"
      - name: "product-svc"
        url: "http://${spring.cloud.inetutils.default-hostname}:${server.port}/api/v1/product/api-docs"
    use-root-path: true
logging:
  level:
    org.springframework.security: DEBUG