apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-svc
  template:
    metadata:
      labels:
        app: gateway-svc
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: gateway-svc
          image: ghcr.io/ngodat0103/yamp/gateway-svc:pr-latest
          imagePullPolicy: Always
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: demo
          ports:
            - containerPort: 8000