spring:
  security:
    oauth2:
      client:
        provider:
          auth-service-internal:
            token-uri: http://auth-svc:8001/api/v1/auth/oauth2/token
          auth-service-external:
            authorization-uri: http://${spring.cloud.inetutils.default-hostname}:8000/api/v1/auth/oauth2/authorize
            token-uri: http://${spring.cloud.inetutils.default-hostname}:8000/api/v1/auth/oauth2/token
            jwk-set-uri: http://${spring.cloud.inetutils.default-hostname}:8000/api/v1/auth/oauth2/jwks
  config:
    activate:
      on-profile: integration-test
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true