spring:
  config:
    activate:
      on-profile: prod
  cloud:
    inetutils:
      default-hostname: yamp-backend.ngodat0103.live
  data:
    redis:
      url: redis://redis-svc-master:6379
  datasource:
    url: jdbc:postgresql://share-db-postgresql:5432/user-svc-db
  kafka:
    bootstrap-servers: kafka-svc:9092.prod-infra-yamp.cluster.local
  jpa:
    hibernate:
      ddl-auto:  update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      client:
        provider:
          auth-service-internal:
            token-uri: http://auth-svc:8001/api/v1/auth/oauth2/token
          auth-service-external:
            authorization-uri: https://${spring.cloud.inetutils.default-hostname}/api/v1/auth/oauth2/authorize
            token-uri: https://${spring.cloud.inetutils.default-hostname}/api/v1/auth/oauth2/token
            jwk-set-uri: https://${spring.cloud.inetutils.default-hostname}/api/v1/auth/oauth2/jwks
        registration:
          user-service:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            scope: auth-service.write,auth-service.read
            provider: auth-service-internal
            client-name: User Service
            client-authentication-method: client_secret_basic
            authorization-grant-type: client_credentials