spring:
  config:
    activate:
      on-profile: integration-test
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
logging:
  level:
    org.springframework.security: DEBUG
    com.github.ngodat0103.yamp.productsvc.service: DEBUG