spring:
  cloud:
    inetutils:
      default-hostname: yamp-backend.local
  config:
    activate:
      on-profile: 'local-dev'
  security:
    oauth2:
      client:
        provider:
          auth-service-external:
            authorization-uri: http://${spring.cloud.inetutils.default-hostname}:8000/api/v1/auth/oauth2/authorize
            token-uri: http://${spring.cloud.inetutils.default-hostname}:8000/api/v1/auth/oauth2/token
            jwk-set-uri: http://${spring.cloud.inetutils.default-hostname}:8000/api/v1/auth/oauth2/jwks

  datasource:
    url: jdbc:postgresql://localhost:5432/product-svc-db
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect