spring:
  config:
    activate:
      on-profile: unit-test
  jpa:
    show-sql: true
logging:
  level:
    org.springframework.security: DEBUG
    com.github.ngodat0103.yamp..productsvc.service: DEBUG
    com.github.ngodat0103.yamp..productsvc.controller: DEBUG
