name: Gateway-svc webhook
on:
  workflow_dispatch:
  push:
    branches:
      - "dev"
    paths:
      - "auth-svc-svc/**"
  pull_request_target:
    types: [ opened,reopened ]
    branches:
      - "feature/**"
      - "fix/**"
    paths:
      - "gateway-svc/**"
jobs:
  send-webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Send webhook to Jenkins
        uses: distributhor/workflow-webhook@v3.0.7
        with:
          webhook_url: ${{ secrets.WEBHOOK_ENDPOINT }}
          webhook_auth_type: 'bearer'
          webhook_type: 'json'
          webhook_auth: ${{ secrets.WEBHOOK_AUTH_SVC_TOKEN }}