name: ci-push-workflow
on:
  workflow_call:
    inputs:
      SERVICE_NAME:
        description: "name of the service to trigger the CI"
        required: true
        type: string
      SERVICE_PORT:
        description: "port of the service to trigger the CI"
        required: true
        type: string
jobs:
  scan_quality_code:
    name: Unit test and scan quality code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Cache SonarQube packages
        uses: actions/cache@v4.0.2
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@v4.0.2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-v1
      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: mvn clean verify sonar:sonar -Dtest=*UnitTest
  scan_vulnerability:
    needs: [scan_quality_code]
    name: check vulnerability using trivy
    runs-on: ubuntu-latest
    env:
      TRIVY_USERNAME: ${{github.repository_owner}}
      TRIVY_PASSWORD: ${{github.token}}
      CACHE_DIR: /tmp/trivy
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache trivy database
        uses: actions/cache@v4.0.2
        with:
          path: /tmp/trivy
          key: ${{ runner.os }}-trivy
      - name: Set up trivy
        run: |
          wget https://github.com/aquasecurity/trivy/releases/download/v0.53.0/trivy_0.53.0_Linux-64bit.deb
          sudo dpkg -i trivy_0.53.0_Linux-64bit.deb
      - name: Scan file system
        working-directory: ${{inputs.SERVICE_NAME}}
        run: trivy --cache-dir=$CACHE_DIR fs --exit-code 1 --severity HIGH,CRITICAL .
      - name: Scan configuration
        working-directory: ${{inputs.SERVICE_NAME}}
        run: trivy --cache-dir=$CACHE_DIR fs --scanners misconfig --exit-code 1 --severity HIGH,CRITICAL .