on:
  push:
    branches:
      - "features/**"
      - "fix/**"
    paths:
      - "user-svc/**"
  pull_request_target:
    types: [ opened,reopened ]
    branches:
      - "feature/**"
      - "fix/**"
    paths:
      - "user-svc/**"
jobs:
  push:
    name: user-svc-commit
    if: github.event_name == 'push'
    uses: ./.github/workflows/ci-push-workflow-call.yaml
    with:
      SERVICE_NAME: user-svc
      SERVICE_PORT: 8002
    secrets: inherit

  pr-integration-test:
    name: user-svc-integration-test
    if: github.event_name == 'pull_request'
    runs-on: cloud-uit
    services:
      redis-svc:
        image: redis:6.2.6
      share-db:
        image: postgres:16.3-bullseye
        volumes:
          - /home/github-runner/yamp-integration/init.sql:/docker-entrypoint-initdb.d/init.sql
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
      auth-svc:
        image: ghcr.io/ngodat0103/yamp/auth-svc:pr-latest
        env:
          SPRING_PROFILES_ACTIVE: demo
    container:
      image: maven:3.8.4-openjdk-17
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Cache Maven packages
        uses: actions/cache@v4.0.2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-v1-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2-v1-
      - name: Running integration test
        working-directory: auth-svc
        env:
          ENCRYPT_KEY: ${{secrets.ENCRYPT_KEY}}
        run: mvn test -q -Dtest=*IntegrationTest

  pr-push-image:
    name: Push docker image
    if: github.event_name == 'pull_request'
    needs: [pr-integration-test]
    uses: ./.github/workflows/ci-pr-workflow-call.yaml
    with:
      SERVICE_NAME: user-svc
      SERVICE_PORT: 8002
    secrets: inherit